services:
  web:
    build: .
    container_name: syed_web
    env_file:
      - .env
    volumes:
      - ./backend/staticfiles:/app/staticfiles
    networks:
      - default
      - proxy_net
    restart: always
    depends_on:
      - db
      - redis

  worker:
    build: .
    container_name: syed_worker
    command: celery -A backend worker --loglevel=info
    env_file:
      - .env
    networks:
      - default
    restart: always
    depends_on:
      - db
      - redis

  beat:
    build: .
    container_name: syed_beat
    command: celery -A backend beat --loglevel=info --schedule=/tmp/celerybeat-schedule
    env_file:
      - .env
    networks:
      - default
    restart: always
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: syed_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "127.0.0.1:5433:5432"
    restart: always

  redis:
    image: redis:7-alpine
    container_name: syed_redis
    restart: always

networks:
  proxy_net:
    external: true

volumes:
  postgres_data:
