services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./Frontend:/app/Frontend
    environment:
      - DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A backend worker --loglevel=info
    volumes:
      - ./backend:/app
      - ./Frontend:/app/Frontend
    environment:
      - DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis

  beat:
    build: .
    command: celery -A backend beat --loglevel=info --schedule=/tmp/celerybeat-schedule
    volumes:
      - ./backend:/app
      - ./Frontend:/app/Frontend
    environment:
      - DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: unless-stopped
