"""End-to-end API tests for the finance module.

Focus areas (the things finance/QA will scrutinise):
  * profit/loss arithmetic and the Received + Outstanding == Revenue identity
  * the partial-payment ledger (knock-offs, running balance)
  * immutability / integrity rules (no voucher delete, locked money fields,
    append-only payments)
  * export (PDF/Excel) and Excel import round-trips
"""
from datetime import date
from decimal import Decimal
from io import BytesIO

from django.core.files.uploadedfile import SimpleUploadedFile
from django.contrib.auth.models import User
from rest_framework import status
from rest_framework.test import APITestCase
from openpyxl import Workbook

from .models import (
    Customer, GeneralVoucher, OfficeExpense, Payment,
    Item, SaleOrder, Shipment,
)


def make_png():
    # Minimal 1x1 PNG so ImageField validation (Pillow) passes.
    import base64
    data = base64.b64decode(
        'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==')
    return SimpleUploadedFile('p.png', data, content_type='image/png')


def make_xlsx(headers, rows):
    wb = Workbook()
    ws = wb.active
    ws.append(headers)
    for r in rows:
        ws.append(r)
    buf = BytesIO()
    wb.save(buf)
    buf.seek(0)
    return SimpleUploadedFile(
        'import.xlsx', buf.getvalue(),
        content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')


class AuthenticatedAPITestCase(APITestCase):
    def setUp(self):
        super().setUp()
        self.dashboard_user = User.objects.create_user(
            username='finance@example.com', password='TestPass!482'
        )
        self.client.force_authenticate(self.dashboard_user)


class FinanceApiTests(AuthenticatedAPITestCase):
    def setUp(self):
        super().setUp()
        self.customer = Customer.objects.create(
            name='Ali', sur_name='Khan', cnic='35202-1234567-1',
            contact_number='03001234567', address='123 St', city='Lahore',
            customer_category='retail',
        )

    def _voucher(self, **kw):
        defaults = dict(
            invoice_number='INV', invoice_date='2026-06-01',
            customer=self.customer, payment_type='credit',
            amount=Decimal('1000.00'))
        defaults.update(kw)
        v = GeneralVoucher.objects.create(**defaults)
        v.recompute_paid()
        return v

    # ---- Customer CRUD ----
    def test_create_customer_with_meta(self):
        resp = self.client.post('/api/finance/customers/', {
            'name': 'Sara', 'sur_name': 'Ahmed', 'cnic': '35202-7654321-2',
            'contact_number': '03007654321', 'address': '9 Mall Rd',
            'city': 'Karachi', 'customer_category': 'wholesale',
            'email': 'sara@example.com', 'meta_data': {'gst': 'X-1'},
        }, format='json')
        self.assertEqual(resp.status_code, status.HTTP_201_CREATED)
        self.assertEqual(resp.data['meta_data']['gst'], 'X-1')

    def test_protected_customer_delete(self):
        self._voucher(invoice_number='INV-1', amount=Decimal('100'))
        resp = self.client.delete(f'/api/finance/customers/{self.customer.id}/')
        self.assertEqual(resp.status_code, status.HTTP_409_CONFLICT)
        self.assertTrue(Customer.objects.filter(id=self.customer.id).exists())

    # ---- Voucher integrity ----
    def test_voucher_cannot_be_deleted(self):
        v = self._voucher(invoice_number='INV-2')
        resp = self.client.delete(f'/api/finance/vouchers/{v.id}/')
        self.assertEqual(resp.status_code, status.HTTP_405_METHOD_NOT_ALLOWED)
        self.assertTrue(GeneralVoucher.objects.filter(id=v.id).exists())

    def test_voucher_money_fields_locked_notes_editable(self):
        other = Customer.objects.create(
            name='Z', sur_name='Z', cnic='1', contact_number='1',
            address='x', city='y')
        v = self._voucher(invoice_number='INV-3', amount=Decimal('500.00'))
        resp = self.client.patch(f'/api/finance/vouchers/{v.id}/', {
            'amount': '9999.00', 'customer': other.id,
            'invoice_number': 'HACKED', 'notes': 'updated note',
        }, format='json')
        self.assertEqual(resp.status_code, status.HTTP_200_OK)
        v.refresh_from_db()
        # Money fields unchanged; only notes applied.
        self.assertEqual(v.amount, Decimal('500.00'))
        self.assertEqual(v.customer_id, self.customer.id)
        self.assertEqual(v.invoice_number, 'INV-3')
        self.assertEqual(v.notes, 'updated note')

    def test_invoice_number_autogenerated(self):
        import re
        resp = self.client.post('/api/finance/vouchers/', {
            'invoice_date': '2026-06-01', 'customer': self.customer.id,
            'payment_type': 'cash', 'amount': '100.00',
        }, format='json')
        self.assertEqual(resp.status_code, status.HTTP_201_CREATED)
        inv = resp.data['invoice_number']
        self.assertRegex(inv, r'^[A-Z]{4}-\d{8}$')

    def test_invoice_numbers_are_unique(self):
        nums = set()
        for _ in range(15):
            r = self.client.post('/api/finance/vouchers/', {
                'invoice_date': '2026-06-01', 'customer': self.customer.id,
                'payment_type': 'cash', 'amount': '10.00'}, format='json')
            nums.add(r.data['invoice_number'])
        self.assertEqual(len(nums), 15)

    def test_client_invoice_number_is_ignored(self):
        # A client cannot dictate the invoice number - it is server-assigned.
        r = self.client.post('/api/finance/vouchers/', {
            'invoice_number': 'HACK-00000001', 'invoice_date': '2026-06-01',
            'customer': self.customer.id, 'payment_type': 'cash',
            'amount': '10.00'}, format='json')
        self.assertNotEqual(r.data['invoice_number'], 'HACK-00000001')
        self.assertRegex(r.data['invoice_number'], r'^[A-Z]{4}-\d{8}$')

    def test_negative_amount_rejected(self):
        resp = self.client.post('/api/finance/vouchers/', {
            'invoice_number': 'NEG-1', 'invoice_date': '2026-06-01',
            'customer': self.customer.id, 'payment_type': 'cash',
            'amount': '-50.00',
        }, format='json')
        self.assertEqual(resp.status_code, status.HTTP_400_BAD_REQUEST)

    # ---- Payments / knock-off ledger ----
    def test_partial_then_full_payment_settles_voucher(self):
        v = self._voucher(invoice_number='PAY-1', amount=Decimal('1000.00'))
        self.assertFalse(v.is_paid)

        r1 = self.client.post('/api/finance/payments/', {
            'voucher': v.id, 'amount': '400.00', 'date': '2026-06-02',
            'method': 'cash'}, format='json')
        self.assertEqual(r1.status_code, status.HTTP_201_CREATED)
        v.refresh_from_db()
        self.assertEqual(v.outstanding, Decimal('600.00'))
        self.assertFalse(v.is_paid)

        r2 = self.client.post('/api/finance/payments/', {
            'voucher': v.id, 'amount': '600.00', 'date': '2026-06-05',
            'method': 'bank'}, format='json')
        self.assertEqual(r2.status_code, status.HTTP_201_CREATED)
        v.refresh_from_db()
        self.assertEqual(v.outstanding, Decimal('0.00'))
        self.assertTrue(v.is_paid)

    def test_overpayment_rejected(self):
        v = self._voucher(invoice_number='PAY-2', amount=Decimal('100.00'))
        resp = self.client.post('/api/finance/payments/', {
            'voucher': v.id, 'amount': '150.00', 'date': '2026-06-02'},
            format='json')
        self.assertEqual(resp.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertEqual(Payment.objects.count(), 0)

    def test_payment_on_debit_voucher_rejected(self):
        v = self._voucher(invoice_number='DBT-1', payment_type='debit',
                          amount=Decimal('100.00'))
        self.assertTrue(v.is_paid)  # debit auto-settled
        resp = self.client.post('/api/finance/payments/', {
            'voucher': v.id, 'amount': '10.00', 'date': '2026-06-02'},
            format='json')
        self.assertEqual(resp.status_code, status.HTTP_400_BAD_REQUEST)

    def test_payment_is_immutable(self):
        v = self._voucher(invoice_number='PAY-3', amount=Decimal('100.00'))
        p = Payment.objects.create(voucher=v, amount=Decimal('50'),
                                   date='2026-06-02')
        self.assertEqual(
            self.client.put(f'/api/finance/payments/{p.id}/',
                            {'amount': '1'}, format='json').status_code,
            status.HTTP_405_METHOD_NOT_ALLOWED)
        self.assertEqual(
            self.client.delete(f'/api/finance/payments/{p.id}/').status_code,
            status.HTTP_405_METHOD_NOT_ALLOWED)

    # ---- Dashboard money math ----
    def test_dashboard_reconciliation(self):
        # Invoices: 1000 + 600 (credit) + 400 (debit, negative) = revenue 1200
        self._voucher(invoice_number='V-1', invoice_date='2026-06-01',
                      payment_type='cash', amount=Decimal('1000.00'))
        v2 = self._voucher(invoice_number='V-2', invoice_date='2026-06-05',
                           payment_type='credit', amount=Decimal('600.00'))
        self._voucher(invoice_number='V-3', invoice_date='2026-06-10',
                      payment_type='debit', amount=Decimal('400.00'))
        # Pay 700 against V-2's 600? no - pay 500 against V-2.
        Payment.objects.create(voucher=v2, amount=Decimal('500.00'),
                               date='2026-06-12')
        v2.recompute_paid()
        OfficeExpense.objects.create(name='Rent', amount=Decimal('300.00'),
                                     date='2026-06-02', expense_type='rent')

        resp = self.client.get('/api/finance/dashboard-summary/')
        t = resp.data['totals']
        self.assertEqual(Decimal(t['revenue']), Decimal('1200.00'))  # 1000+600-400
        self.assertEqual(Decimal(t['received']), Decimal('500.00'))   # one payment
        self.assertEqual(Decimal(t['outstanding']), Decimal('700.00'))  # 1200-500
        self.assertEqual(Decimal(t['expenses']), Decimal('300.00'))
        self.assertEqual(Decimal(t['net_profit']), Decimal('900.00'))   # 1200-300
        # All-time reconciliation identity.
        self.assertEqual(Decimal(t['received']) + Decimal(t['outstanding']),
                         Decimal(t['revenue']))

    def test_dashboard_loss_case(self):
        self._voucher(invoice_number='L-1', payment_type='cash',
                      amount=Decimal('100.00'))
        OfficeExpense.objects.create(name='Big', amount=Decimal('500.00'),
                                     date='2026-06-02', expense_type='other')
        t = self.client.get('/api/finance/dashboard-summary/').data['totals']
        self.assertEqual(Decimal(t['net_profit']), Decimal('-400.00'))
        self.assertFalse(t['is_profit'])

    def test_debit_voucher_reduces_outstanding(self):
        # A debit note's outstanding is negative - it reduces the receivable
        # so that Total billed − Received = Outstanding stays exact.
        v = GeneralVoucher.objects.create(
            invoice_number='ADJ-1', invoice_date='2026-06-01',
            customer=self.customer, payment_type='debit',
            amount=Decimal('5020.00'))
        self.assertEqual(v.outstanding, Decimal('-5020.00'))

    def test_debit_signed_amount(self):
        v = self._voucher(invoice_number='DB-2', payment_type='debit',
                          amount=Decimal('250.00'))
        resp = self.client.get(f'/api/finance/vouchers/{v.id}/')
        self.assertEqual(Decimal(resp.data['amount']), Decimal('250.00'))
        self.assertEqual(Decimal(resp.data['signed_amount']), Decimal('-250.00'))

    # ---- Customer ledger ----
    def test_customer_ledger_running_balance(self):
        v = self._voucher(invoice_number='LG-1', amount=Decimal('1000.00'),
                          invoice_date='2026-06-01')
        Payment.objects.create(voucher=v, amount=Decimal('400.00'),
                               date='2026-06-03')
        resp = self.client.get(
            f'/api/finance/customers/{self.customer.id}/ledger/')
        self.assertEqual(resp.status_code, status.HTTP_200_OK)
        lines = resp.data['lines']
        self.assertEqual(len(lines), 2)
        self.assertEqual(lines[0]['debit'], '1000.00')   # invoice
        self.assertEqual(lines[0]['balance'], '1000.00')
        self.assertEqual(lines[1]['credit'], '400.00')   # payment
        self.assertEqual(lines[1]['balance'], '600.00')
        self.assertEqual(resp.data['totals']['balance'], '600.00')

    # ---- Export ----
    def test_exports_return_files(self):
        self._voucher(invoice_number='EX-1', amount=Decimal('100'))
        OfficeExpense.objects.create(name='X', amount=Decimal('5'),
                                     date='2026-06-01', expense_type='other')
        xlsx = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        cases = [
            ('/api/finance/vouchers/export/?fmt=excel', xlsx),
            ('/api/finance/vouchers/export/?fmt=pdf', 'application/pdf'),
            ('/api/finance/expenses/export/?fmt=excel', xlsx),
            ('/api/finance/customers/export/?fmt=pdf', 'application/pdf'),
            (f'/api/finance/customers/{self.customer.id}/statement/?fmt=pdf',
             'application/pdf'),
            (f'/api/finance/customers/{self.customer.id}/statement/?fmt=excel',
             xlsx),
        ]
        for url, ctype in cases:
            r = self.client.get(url)
            self.assertEqual(r.status_code, 200, url)
            self.assertEqual(r['Content-Type'], ctype, url)
            self.assertTrue(len(r.content) > 100, url)

    # ---- Import ----
    def test_single_invoice_download(self):
        v = self._voucher(invoice_number='INV-DL', amount=Decimal('500'))
        Payment.objects.create(voucher=v, amount=Decimal('200'), date='2026-06-02')
        pdf = self.client.get(f'/api/finance/vouchers/{v.id}/invoice/?fmt=pdf')
        self.assertEqual(pdf.status_code, 200)
        self.assertEqual(pdf['Content-Type'], 'application/pdf')
        self.assertTrue(len(pdf.content) > 500)
        xl = self.client.get(f'/api/finance/vouchers/{v.id}/invoice/?fmt=excel')
        self.assertEqual(xl.status_code, 200)
        self.assertIn('spreadsheet', xl['Content-Type'])

    def test_import_customers_excel(self):
        f = make_xlsx(
            ['Name', 'Surname', 'CNIC', 'Contact', 'City', 'Category', 'Email'],
            [['Bilal', 'Tariq', '11111-1111111-1', '03110000000', 'Multan',
              'Wholesale', 'b@x.com']])
        r = self.client.post('/api/finance/customers/import_data/',
                             {'file': f}, format='multipart')
        self.assertEqual(r.status_code, 200)
        self.assertEqual(r.data['created'], 1)
        self.assertTrue(Customer.objects.filter(cnic='11111-1111111-1').exists())

    def test_import_vouchers_excel_matches_customer(self):
        f = make_xlsx(
            ['Invoice #', 'Date', 'CNIC', 'Payment Type', 'Amount', 'Due Date'],
            [['IMP-1', '2026-06-01', '35202-1234567-1', 'Credit', '1500', '']])
        r = self.client.post('/api/finance/vouchers/import_data/',
                             {'file': f}, format='multipart')
        self.assertEqual(r.status_code, 200)
        self.assertEqual(r.data['created'], 1)
        v = GeneralVoucher.objects.get(invoice_number='IMP-1')
        self.assertEqual(v.amount, Decimal('1500'))
        self.assertEqual(v.customer_id, self.customer.id)

    def test_import_expenses_excel(self):
        f = make_xlsx(
            ['Name', 'Type', 'Amount', 'Date'],
            [['Office Rent', 'Rent', '25000', '2026-06-01']])
        r = self.client.post('/api/finance/expenses/import_data/',
                             {'file': f}, format='multipart')
        self.assertEqual(r.status_code, 200)
        self.assertEqual(r.data['created'], 1)
        self.assertTrue(OfficeExpense.objects.filter(name='Office Rent').exists())


class EmployeeTests(AuthenticatedAPITestCase):
    def test_employee_crud_and_search(self):
        r = self.client.post('/api/finance/employees/', {
            'name': 'Bilal', 'designation': 'Driver',
            'phone_number': '03001234567', 'cnic': '35202-1111111-1',
            'salary': '45000', 'email': 'bilal@x.com', 'address': 'Lahore',
        }, format='json')
        self.assertEqual(r.status_code, status.HTTP_201_CREATED)
        eid = r.data['id']
        self.assertEqual(Decimal(r.data['salary']), Decimal('45000'))

        # search
        s = self.client.get('/api/finance/employees/?search=driver')
        self.assertEqual(len(s.data), 1)

        # update
        u = self.client.patch(f'/api/finance/employees/{eid}/',
                              {'salary': '50000'}, format='json')
        self.assertEqual(Decimal(u.data['salary']), Decimal('50000'))

        # delete
        d = self.client.delete(f'/api/finance/employees/{eid}/')
        self.assertEqual(d.status_code, status.HTTP_204_NO_CONTENT)

    def test_employee_negative_salary_rejected(self):
        r = self.client.post('/api/finance/employees/', {
            'name': 'X', 'designation': 'Y', 'phone_number': '1',
            'cnic': '1', 'salary': '-5',
        }, format='json')
        self.assertEqual(r.status_code, status.HTTP_400_BAD_REQUEST)


class SaleOrderTests(AuthenticatedAPITestCase):
    def setUp(self):
        super().setUp()
        self.customer = Customer.objects.create(
            name='Ali', sur_name='Khan', cnic='35202-1234567-1',
            contact_number='03001234567', address='123 St', city='Lahore')
        self.item = Item.objects.create(
            sku='LMS-BOX-01', name='LMS Box', weight_kg=Decimal('12.000'),
            amount=Decimal('8000.00'))

    def _order(self, lines=None):
        lines = lines or [
            {'item': self.item.id, 'name': 'LMS Box', 'sku': 'LMS-BOX-01',
             'weight_kg': '12', 'amount': '8000'},
            {'name': 'LMS Pallet', 'sku': 'LMS-PAL', 'weight_kg': '40',
             'amount': '32000'},
        ]
        return self.client.post('/api/finance/sale-orders/', {
            'customer': self.customer.id, 'shipment_number': 'SHIP-001',
            'order_date': '2026-06-01', 'items': lines,
        }, format='json')

    def test_item_search(self):
        Item.objects.create(sku='ABC-1', name='Other', amount=Decimal('5'))
        r = self.client.get('/api/finance/items/?search=lms')
        self.assertEqual(len(r.data), 1)
        self.assertEqual(r.data[0]['sku'], 'LMS-BOX-01')

    def test_create_order_computes_total_and_invoice(self):
        r = self._order()
        self.assertEqual(r.status_code, status.HTTP_201_CREATED)
        self.assertEqual(Decimal(r.data['total_amount']), Decimal('40000.00'))
        self.assertRegex(r.data['invoice_number'], r'^[A-Z]{4}-\d{8}$')
        self.assertEqual(len(r.data['items']), 2)
        self.assertEqual(Decimal(r.data['outstanding']), Decimal('40000.00'))

    def test_order_requires_items(self):
        r = self.client.post('/api/finance/sale-orders/', {
            'customer': self.customer.id, 'order_date': '2026-06-01',
            'items': []}, format='json')
        self.assertEqual(r.status_code, status.HTTP_400_BAD_REQUEST)

    def test_order_cannot_be_deleted(self):
        oid = self._order().data['id']
        r = self.client.delete(f'/api/finance/sale-orders/{oid}/')
        self.assertEqual(r.status_code, status.HTTP_405_METHOD_NOT_ALLOWED)

    def test_order_items_locked_on_edit(self):
        oid = self._order().data['id']
        r = self.client.patch(f'/api/finance/sale-orders/{oid}/', {
            'shipment_number': 'SHIP-XYZ',
            'items': [{'name': 'Hacked', 'amount': '1'}],
        }, format='json')
        self.assertEqual(r.status_code, status.HTTP_200_OK)
        so = SaleOrder.objects.get(id=oid)
        self.assertEqual(so.shipment_number, 'SHIP-XYZ')       # editable
        self.assertEqual(so.total_amount, Decimal('40000.00'))  # locked
        self.assertEqual(so.items.count(), 2)

    def test_receipt_voucher_knocks_off_order(self):
        order = self._order().data
        oid = order['id']
        # Order should appear in the open list for the voucher dropdown.
        openr = self.client.get('/api/finance/sale-orders/open/')
        self.assertTrue(any(o['id'] == oid for o in openr.data))

        # Record a receipt voucher of 15000 against the order.
        r = self.client.post('/api/finance/vouchers/', {
            'invoice_date': '2026-06-05', 'payment_type': 'cash',
            'amount': '15000', 'sale_order': oid}, format='json')
        self.assertEqual(r.status_code, status.HTTP_201_CREATED)
        self.assertTrue(r.data['is_receipt'])
        # Customer auto-filled from the order.
        self.assertEqual(r.data['customer'], self.customer.id)

        so = SaleOrder.objects.get(id=oid)
        self.assertEqual(so.amount_received, Decimal('15000.00'))
        self.assertEqual(so.outstanding, Decimal('25000.00'))

    def test_receipt_cannot_exceed_order_balance(self):
        oid = self._order().data['id']
        r = self.client.post('/api/finance/vouchers/', {
            'invoice_date': '2026-06-05', 'payment_type': 'cash',
            'amount': '999999', 'sale_order': oid}, format='json')
        self.assertEqual(r.status_code, status.HTTP_400_BAD_REQUEST)

    def test_payment_blocked_on_receipt_voucher(self):
        oid = self._order().data['id']
        v = self.client.post('/api/finance/vouchers/', {
            'invoice_date': '2026-06-05', 'payment_type': 'cash',
            'amount': '1000', 'sale_order': oid}, format='json').data
        r = self.client.post('/api/finance/payments/', {
            'voucher': v['id'], 'amount': '100', 'date': '2026-06-06'},
            format='json')
        self.assertEqual(r.status_code, status.HTTP_400_BAD_REQUEST)

    def test_ledger_with_order_and_receipt(self):
        oid = self._order().data['id']
        self.client.post('/api/finance/vouchers/', {
            'invoice_date': '2026-06-05', 'payment_type': 'cash',
            'amount': '10000', 'sale_order': oid}, format='json')
        r = self.client.get(
            f'/api/finance/customers/{self.customer.id}/ledger/')
        t = r.data['totals']
        self.assertEqual(Decimal(t['debit']), Decimal('40000.00'))   # order
        self.assertEqual(Decimal(t['credit']), Decimal('10000.00'))  # receipt
        self.assertEqual(Decimal(t['balance']), Decimal('30000.00'))

    def test_create_shipment_with_customers_and_items(self):
        c2 = Customer.objects.create(
            name='Sara', sur_name='Ahmed', cnic='9', contact_number='9',
            address='x', city='Karachi')
        r = self.client.post('/api/finance/shipments/', {
            'shipment_date': '2026-06-01',
            'status': 'pending',
            'customers': [self.customer.id, c2.id],
            'items': [
                {'item': self.item.id, 'name': 'LMS Box', 'sku': 'LMS-BOX-01',
                 'weight_kg': '12', 'quantity': 2},
            ],
        }, format='json')
        self.assertEqual(r.status_code, status.HTTP_201_CREATED)
        self.assertRegex(r.data['shipment_id'], r'^SHP-\d{8}$')
        self.assertEqual(len(r.data['customers']), 2)        # multiple customers
        self.assertEqual(len(r.data['items']), 1)
        self.assertEqual(Decimal(r.data['total_weight']), Decimal('24.000'))  # 12*2

    def test_shipment_image_upload_and_delete(self):
        sid = self.client.post('/api/finance/shipments/', {
            'shipment_date': '2026-06-01', 'customers': [self.customer.id],
        }, format='json').data['id']
        up = self.client.post(
            f'/api/finance/shipments/{sid}/upload_images/',
            {'images': [make_png(), make_png()]}, format='multipart')
        self.assertEqual(up.status_code, status.HTTP_201_CREATED)
        self.assertEqual(len(up.data['images']), 2)
        img_id = up.data['images'][0]['id']
        d = self.client.delete(
            f'/api/finance/shipments/{sid}/images/{img_id}/')
        self.assertEqual(d.status_code, status.HTTP_204_NO_CONTENT)
        s = Shipment.objects.get(id=sid)
        self.assertEqual(s.images.count(), 1)

    def test_sale_order_links_shipment(self):
        sid = self.client.post('/api/finance/shipments/', {
            'shipment_date': '2026-06-01', 'customers': [self.customer.id],
        }, format='json').data
        r = self.client.post('/api/finance/sale-orders/', {
            'customer': self.customer.id, 'order_date': '2026-06-02',
            'shipment': sid['id'],
            'items': [{'name': 'X', 'amount': '100', 'weight_kg': '1'}],
        }, format='json')
        self.assertEqual(r.status_code, status.HTTP_201_CREATED)
        self.assertEqual(r.data['shipment'], sid['id'])
        self.assertEqual(r.data['shipment_code'], sid['shipment_id'])
        # shipment_number mirrors the shipment id for display.
        self.assertEqual(r.data['shipment_number'], sid['shipment_id'])

    def test_shipment_options_list(self):
        self.client.post('/api/finance/shipments/', {
            'shipment_date': '2026-06-01', 'customers': [self.customer.id],
        }, format='json')
        r = self.client.get('/api/finance/shipments/options_list/')
        self.assertEqual(r.status_code, status.HTTP_200_OK)
        self.assertEqual(len(r.data), 1)
        self.assertIn('shipment_id', r.data[0])

    def test_dashboard_reconciliation_with_orders(self):
        oid = self._order().data['id']  # 40000 debit
        self.client.post('/api/finance/vouchers/', {
            'invoice_date': '2026-06-05', 'payment_type': 'cash',
            'amount': '10000', 'sale_order': oid}, format='json')  # 10000 received
        OfficeExpense.objects.create(name='Rent', amount=Decimal('5000'),
                                     date='2026-06-02', expense_type='rent')
        t = self.client.get('/api/finance/dashboard-summary/').data['totals']
        self.assertEqual(Decimal(t['revenue']), Decimal('40000.00'))
        self.assertEqual(Decimal(t['received']), Decimal('10000.00'))
        self.assertEqual(Decimal(t['outstanding']), Decimal('30000.00'))
        self.assertEqual(Decimal(t['net_profit']), Decimal('35000.00'))  # 40000-5000
        self.assertEqual(Decimal(t['received']) + Decimal(t['outstanding']),
                         Decimal(t['revenue']))


# --------------------------------------------------------------------------
# Invoice & salary-slip generator
# --------------------------------------------------------------------------
import uuid as _uuid

from rest_framework.test import APIClient

from .models import (
    CompanyProfile, Employee, Invoice, SalarySlip,
    compute_invoice_totals, compute_salary_totals,
)


def invoice_payload(**overrides):
    data = {
        'invoice_date': '2026-10-06',
        'bill_to_name': 'Tanmy Sharma',
        'bill_to_phone': '0300 1234567',
        'origin': 'Lahore',
        'destination': 'Karachi',
        'transport_mode': 'road',
        'items': [
            {'description': 'Freight charges', 'quantity': '2', 'rate': '1500.00'},
            {'description': 'Loading', 'unit': 'trip', 'quantity': '1', 'rate': '999.99'},
        ],
        'discount': '99.99',
        'other_charges_label': 'Toll',
        'other_charges': '100',
        'tax_percent': '5',
        'advance_amount': '1000',
        'advance_date': '2026-10-06',
        'balance_due_date': '2026-10-20',
        'payment_method': 'cash',
    }
    data.update(overrides)
    return data


def slip_payload(**overrides):
    data = {
        'employee_name': 'Ali Raza',
        'designation': 'Driver',
        'pay_period_start': '2026-09-01',
        'pay_period_end': '2026-09-30',
        'pay_date': '2026-10-01',
        'working_days': '26',
        'days_present': '25',
        'basic_salary': '50000',
        'tax_percent': '2',
        'lines': [
            {'kind': 'earning', 'label': 'House rent', 'amount': '5000'},
            {'kind': 'earning', 'label': 'Overtime', 'amount': '2500'},
            {'kind': 'deduction', 'label': 'Advance recovery', 'amount': '1000'},
        ],
        'payment_status': 'paid',
        'payment_method': 'bank',
        'bank_name': 'Meezan Bank',
        'bank_account_number': 'PK00MEZN0000000000000000',
        'transaction_id': 'TXN-889',
    }
    data.update(overrides)
    return data


class DocumentCalculationTests(APITestCase):
    def test_invoice_totals(self):
        t = compute_invoice_totals(
            [(2, Decimal('1500')), (1, Decimal('999.99'))],
            discount=Decimal('99.99'), tax_percent=Decimal('5'),
            other_charges=Decimal('100'), advance_amount=Decimal('1000'))
        self.assertEqual(t['subtotal'], Decimal('3999.99'))
        self.assertEqual(t['tax_amount'], Decimal('200.00'))
        self.assertEqual(t['total_amount'], Decimal('4200.00'))
        self.assertEqual(t['balance_due'], Decimal('3200.00'))

    def test_invoice_rounding_half_up(self):
        t = compute_invoice_totals([(Decimal('0.333'), Decimal('10.05'))])
        self.assertEqual(t['subtotal'], Decimal('3.35'))  # 3.34665 -> 3.35

    def test_salary_totals_percent_and_fixed_tax(self):
        t = compute_salary_totals(Decimal('50000'), [Decimal('5000'), Decimal('2500')],
                                  [Decimal('1000')], tax_percent=Decimal('2'))
        self.assertEqual(t['gross_earnings'], Decimal('57500.00'))
        self.assertEqual(t['tax_amount'], Decimal('1150.00'))
        self.assertEqual(t['total_deductions'], Decimal('2150.00'))
        self.assertEqual(t['net_pay'], Decimal('55350.00'))
        fixed = compute_salary_totals(Decimal('30000'), [], [], tax_amount=Decimal('750'))
        self.assertEqual(fixed['net_pay'], Decimal('29250.00'))


class InvoiceApiTests(AuthenticatedAPITestCase):
    url = '/api/finance/invoices/'

    def create(self, **overrides):
        res = self.client.post(self.url, invoice_payload(**overrides), format='json')
        self.assertEqual(res.status_code, status.HTTP_201_CREATED, res.data)
        return res.data

    def test_create_computes_totals_and_numbers(self):
        inv = self.create()
        self.assertEqual(inv['invoice_number'], 'INV-2026-0001')
        self.assertEqual(inv['subtotal'], '3999.99')
        self.assertEqual(inv['tax_amount'], '200.00')
        self.assertEqual(inv['total_amount'], '4200.00')
        self.assertEqual(inv['amount_paid'], '1000.00')
        self.assertEqual(inv['balance_due'], '3200.00')
        self.assertEqual(inv['advance_date'], '2026-10-06')
        self.assertEqual(inv['balance_due_date'], '2026-10-20')
        self.assertEqual(inv['payment_status'], 'partial')
        self.assertEqual([i['amount'] for i in inv['items']], ['3000.00', '999.99'])
        self.assertTrue(inv['share_token'])
        self.assertEqual(self.create()['invoice_number'], 'INV-2026-0002')

    def test_client_totals_are_ignored(self):
        inv = self.create(total_amount='1.00', balance_due='0', subtotal='5')
        self.assertEqual(inv['total_amount'], '4200.00')
        self.assertEqual(inv['balance_due'], '3200.00')

    def test_custom_number_and_next_number(self):
        self.create(invoice_number='SLI-7')
        res = self.client.get(self.url + 'next_number/', {'date': '2026-01-01'})
        self.assertEqual(res.data['number'], 'INV-2026-0001')
        dup = self.client.post(self.url, invoice_payload(invoice_number='SLI-7'), format='json')
        self.assertEqual(dup.status_code, status.HTTP_400_BAD_REQUEST)

    def test_validation(self):
        cases = [
            invoice_payload(items=[]),
            invoice_payload(advance_date=None),             # advance without date
            invoice_payload(advance_amount='5000'),          # more than total
            invoice_payload(discount='100000'),              # negative total
            invoice_payload(discount='-1'),
            invoice_payload(bill_to_name=''),
            invoice_payload(items=[{'description': 'x', 'quantity': '-1', 'rate': '10'}]),
        ]
        for payload in cases:
            res = self.client.post(self.url, payload, format='json')
            self.assertEqual(res.status_code, status.HTTP_400_BAD_REQUEST, payload)
        self.assertEqual(Invoice.objects.count(), 0)

    def test_update_replaces_items_and_patch_recomputes(self):
        inv = self.create()
        res = self.client.put(self.url + f"{inv['id']}/", invoice_payload(
            items=[{'description': 'Air freight', 'quantity': '1', 'rate': '10000'}],
            discount='0', other_charges='0', tax_percent='0'), format='json')
        self.assertEqual(res.status_code, 200, res.data)
        self.assertEqual(len(res.data['items']), 1)
        self.assertEqual(res.data['invoice_number'], inv['invoice_number'])
        self.assertEqual(res.data['balance_due'], '9000.00')
        # PATCH without items: totals recomputed from the stored lines.
        res = self.client.patch(self.url + f"{inv['id']}/", {
            'amount_received': '9000', 'received_date': '2026-10-15',
            'payment_method': 'bank', 'transaction_reference': 'IBFT-1'}, format='json')
        self.assertEqual(res.status_code, 200, res.data)
        self.assertEqual(res.data['balance_due'], '0.00')
        self.assertEqual(res.data['payment_status'], 'paid')

    def test_status_and_search_filters(self):
        self.create()                                                   # partial
        self.create(advance_amount='0', advance_date=None,
                    bill_to_name='Unpaid Co')                           # unpaid
        self.create(advance_amount='4200', bill_to_name='Paid Co')      # paid
        get = lambda **p: [i['bill_to_name'] for i in self.client.get(self.url, p).data]  # noqa: E731
        self.assertEqual(get(status='paid'), ['Paid Co'])
        self.assertEqual(get(status='unpaid'), ['Unpaid Co'])
        self.assertEqual(get(status='partial'), ['Tanmy Sharma'])
        self.assertEqual(get(search='unpaid'), ['Unpaid Co'])
        self.assertEqual(len(get(**{'from': '2026-10-07'})), 0)

    def test_does_not_touch_ledger_or_dashboard(self):
        before = self.client.get('/api/finance/dashboard-summary/').data
        self.create()
        after = self.client.get('/api/finance/dashboard-summary/').data
        self.assertEqual(before, after)
        self.assertEqual(GeneralVoucher.objects.count(), 0)

    def test_customer_can_still_be_deleted(self):
        customer = Customer.objects.create(
            name='Ali', sur_name='Khan', cnic='1', contact_number='0300',
            address='Mall Road', city='Lahore')
        inv = self.create(customer=customer.id)
        res = self.client.delete(f'/api/finance/customers/{customer.id}/')
        self.assertEqual(res.status_code, status.HTTP_204_NO_CONTENT)
        invoice = Invoice.objects.get(pk=inv['id'])
        self.assertIsNone(invoice.customer)
        self.assertEqual(invoice.bill_to_name, 'Tanmy Sharma')

    def test_delete(self):
        inv = self.create()
        res = self.client.delete(self.url + f"{inv['id']}/")
        self.assertEqual(res.status_code, status.HTTP_204_NO_CONTENT)
        self.assertFalse(Invoice.objects.exists())

    def test_requires_login(self):
        anon = APIClient()
        self.assertIn(anon.get(self.url).status_code, (401, 403))
        self.assertIn(anon.post(self.url, invoice_payload(), format='json').status_code, (401, 403))
        self.assertIn(anon.get('/api/finance/salary-slips/').status_code, (401, 403))
        self.assertIn(anon.get('/api/finance/company-profile/').status_code, (401, 403))

    def test_public_share_page(self):
        inv = self.create()
        anon = APIClient()
        res = anon.get(f"/share/invoice/{inv['share_token']}/")
        self.assertEqual(res.status_code, 200)
        self.assertContains(res, 'INV-2026-0001')
        self.assertContains(res, 'doc-data')
        self.assertEqual(anon.get(f'/share/invoice/{_uuid.uuid4()}/').status_code, 404)
        self.assertEqual(anon.get(f"/share/invoice/{inv['id']}/").status_code, 404)


class SalarySlipApiTests(AuthenticatedAPITestCase):
    url = '/api/finance/salary-slips/'

    def setUp(self):
        super().setUp()
        self.employee = Employee.objects.create(
            name='Ali Raza', phone_number='03001234567', cnic='35202-1',
            designation='Driver', salary=Decimal('50000'))

    def create(self, **overrides):
        res = self.client.post(self.url, slip_payload(**overrides), format='json')
        self.assertEqual(res.status_code, status.HTTP_201_CREATED, res.data)
        return res.data

    def test_create_computes_net_pay(self):
        slip = self.create(employee=self.employee.id)
        self.assertEqual(slip['slip_number'], 'SAL-2026-0001')
        self.assertEqual(slip['gross_earnings'], '57500.00')
        self.assertEqual(slip['tax_amount'], '1150.00')
        self.assertEqual(slip['total_deductions'], '2150.00')
        self.assertEqual(slip['net_pay'], '55350.00')
        self.assertEqual(slip['payment_method_display'], 'Bank Transfer')
        self.assertEqual(slip['transaction_id'], 'TXN-889')
        self.assertEqual(len(slip['lines']), 3)
        self.assertEqual(self.create()['slip_number'], 'SAL-2026-0002')

    def test_fixed_tax_and_no_lines(self):
        slip = self.create(tax_percent='0', tax_amount='500', lines=[],
                           payment_method='cash', transaction_id='')
        self.assertEqual(slip['net_pay'], '49500.00')

    def test_validation(self):
        for payload in [
            slip_payload(pay_period_end='2026-08-31'),
            slip_payload(lines=[{'kind': 'deduction', 'label': 'x', 'amount': '999999'}]),
            slip_payload(tax_percent='101'),
            slip_payload(basic_salary='-1'),
            slip_payload(lines=[{'kind': 'bonus', 'label': 'x', 'amount': '1'}]),
            slip_payload(employee_name=''),
        ]:
            res = self.client.post(self.url, payload, format='json')
            self.assertEqual(res.status_code, status.HTTP_400_BAD_REQUEST, payload)

    def test_update_lines_and_patch(self):
        slip = self.create()
        res = self.client.put(self.url + f"{slip['id']}/", slip_payload(lines=[]), format='json')
        self.assertEqual(res.status_code, 200, res.data)
        self.assertEqual(res.data['lines'], [])
        self.assertEqual(res.data['net_pay'], '49000.00')
        res = self.client.patch(self.url + f"{slip['id']}/", {'payment_status': 'pending'}, format='json')
        self.assertEqual(res.data['net_pay'], '49000.00')
        self.assertEqual(res.data['payment_status'], 'pending')

    def test_filters(self):
        self.create(employee=self.employee.id)
        self.create(employee_name='Bilal', payment_status='pending',
                    pay_period_start='2026-08-01', pay_period_end='2026-08-31')
        names = lambda **p: [s['employee_name'] for s in self.client.get(self.url, p).data]  # noqa: E731
        self.assertEqual(names(employee=self.employee.id), ['Ali Raza'])
        self.assertEqual(names(status='pending'), ['Bilal'])
        self.assertEqual(names(**{'from': '2026-09-01'}), ['Ali Raza'])
        self.assertEqual(names(search='bil'), ['Bilal'])

    def test_employee_delete_keeps_slip(self):
        slip = self.create(employee=self.employee.id)
        res = self.client.delete(f'/api/finance/employees/{self.employee.id}/')
        self.assertEqual(res.status_code, status.HTTP_204_NO_CONTENT)
        kept = SalarySlip.objects.get(pk=slip['id'])
        self.assertIsNone(kept.employee)
        self.assertEqual(kept.employee_name, 'Ali Raza')

    def test_public_share_page(self):
        slip = self.create()
        res = APIClient().get(f"/share/salary-slip/{slip['share_token']}/")
        self.assertEqual(res.status_code, 200)
        self.assertContains(res, 'SAL-2026-0001')


class EmployeePayrollFieldsTests(AuthenticatedAPITestCase):
    def test_old_payload_still_works_and_new_fields_roundtrip(self):
        base = {'name': 'Sara', 'phone_number': '0300', 'cnic': '1',
                'designation': 'Accountant', 'salary': '60000'}
        res = self.client.post('/api/finance/employees/', base, format='json')
        self.assertEqual(res.status_code, 201, res.data)
        self.assertEqual(res.data['department'], '')
        res = self.client.put(f"/api/finance/employees/{res.data['id']}/", dict(
            base, employee_code='E-7', department='Finance', joining_date='2025-01-15',
            bank_name='HBL', bank_account_title='Sara', bank_account_number='123'), format='json')
        self.assertEqual(res.status_code, 200, res.data)
        self.assertEqual(res.data['joining_date'], '2025-01-15')
        self.assertEqual(res.data['bank_account_number'], '123')


class CompanyProfileTests(AuthenticatedAPITestCase):
    url = '/api/finance/company-profile/'

    def test_defaults_and_update_singleton(self):
        res = self.client.get(self.url)
        self.assertEqual(res.status_code, 200)
        self.assertEqual(res.data['name'], 'Syed Logistic')
        res = self.client.put(self.url, {'bank_name': 'Meezan', 'bank_iban': 'PK36'}, format='json')
        self.assertEqual(res.status_code, 200, res.data)
        self.assertEqual(res.data['bank_name'], 'Meezan')
        self.assertEqual(res.data['name'], 'Syed Logistic')
        self.client.put(self.url, {'phone': '042'}, format='json')
        self.assertEqual(CompanyProfile.objects.count(), 1)
        self.assertEqual(CompanyProfile.load().bank_iban, 'PK36')


class DocumentPagesTests(APITestCase):
    PAGES = ['/invoices/', '/invoices/new/', '/salary-slips/', '/salary-slips/new/']

    def test_pages_require_login_and_render(self):
        for path in self.PAGES:
            self.assertEqual(self.client.get(path).status_code, 302, path)
        user = User.objects.create_user(username='p@example.com', password='TestPass!482')
        self.client.force_login(user)
        for path in self.PAGES + ['/dashboard/', '/employees/']:
            self.assertEqual(self.client.get(path).status_code, 200, path)
        inv = Invoice.objects.create(invoice_date=date(2026, 10, 6), bill_to_name='X')
        slip = SalarySlip.objects.create(
            employee_name='Y', pay_period_start=date(2026, 9, 1), pay_period_end=date(2026, 9, 30))
        res = self.client.get(f'/invoices/{inv.pk}/edit/')
        self.assertContains(res, f'var invoiceId = {inv.pk};')
        res = self.client.get(f'/salary-slips/{slip.pk}/edit/')
        self.assertContains(res, f'var slipId = {slip.pk};')
        self.assertContains(self.client.get('/invoices/new/'), 'var invoiceId = null;')
        self.assertContains(self.client.get('/dashboard/'), '/salary-slips/new/')


class ItemQuantityTests(AuthenticatedAPITestCase):
    url = '/api/finance/items/'

    def test_quantity_default_roundtrip_and_validation(self):
        res = self.client.post(self.url, {'sku': 'Q-1', 'name': 'Pallet'}, format='json')
        self.assertEqual(res.status_code, 201, res.data)
        self.assertEqual(res.data['quantity'], 1)
        res = self.client.put(self.url + f"{res.data['id']}/", {
            'sku': 'Q-1', 'name': 'Pallet', 'quantity': 25}, format='json')
        self.assertEqual(res.status_code, 200, res.data)
        self.assertEqual(Item.objects.get(sku='Q-1').quantity, 25)
        for bad in (-1, 'abc', 1.5):
            res = self.client.post(self.url, {'sku': f'Q-{bad}', 'name': 'x', 'quantity': bad}, format='json')
            self.assertEqual(res.status_code, 400, bad)


import shutil
import tempfile

from django.test import override_settings

from .models import CompanyProfile as Company

TEMP_MEDIA = tempfile.mkdtemp(prefix='sli-media-')


def real_png():
    from PIL import Image
    buf = BytesIO()
    Image.new('RGB', (40, 20), (23, 47, 68)).save(buf, 'PNG')
    return SimpleUploadedFile('logo.png', buf.getvalue(), content_type='image/png')


@override_settings(MEDIA_ROOT=TEMP_MEDIA)
class CompanyLetterheadTests(AuthenticatedAPITestCase):
    url = '/api/finance/companies/'

    @classmethod
    def tearDownClass(cls):
        super().tearDownClass()
        shutil.rmtree(TEMP_MEDIA, ignore_errors=True)

    def invoice(self, **overrides):
        res = self.client.post('/api/finance/invoices/', invoice_payload(**overrides), format='json')
        self.assertEqual(res.status_code, 201, res.data)
        return res.data

    def test_default_company_and_switching(self):
        default = self.client.get(self.url).data
        self.assertEqual(len(default), 1)
        self.assertTrue(default[0]['is_default'])
        self.assertEqual(default[0]['logo_url'], '/static/img/logo.svg')
        res = self.client.post(self.url, {'name': 'Gillani Traders', 'phone': '042-111'}, format='json')
        self.assertEqual(res.status_code, 201, res.data)
        self.assertFalse(res.data['is_default'])
        self.assertEqual(res.data['logo_url'], '')
        res = self.client.post(self.url + f"{res.data['id']}/make_default/")
        self.assertTrue(res.data['is_default'])
        self.assertEqual(Company.objects.filter(is_default=True).count(), 1)
        self.assertEqual(Company.load().name, 'Gillani Traders')
        # The default can't be deleted; another one can.
        self.assertEqual(self.client.delete(self.url + f"{res.data['id']}/").status_code, 409)
        self.assertEqual(self.client.delete(self.url + f"{default[0]['id']}/").status_code, 204)
        self.assertEqual(self.client.post(self.url, {'name': '  '}, format='json').status_code, 400)

    def test_invoice_snapshots_selected_company(self):
        inv = self.invoice()
        self.assertEqual(inv['company'], Company.load().id)
        self.assertEqual(inv['company_details']['name'], 'Syed Logistic')
        self.assertEqual(inv['company_details']['logo'], '/static/img/logo.svg')
        other = Company.objects.create(name='Gillani Traders', phone='042-111', bank_name='HBL')
        inv2 = self.invoice(company=other.id)
        self.assertEqual(inv2['company_details']['name'], 'Gillani Traders')
        self.assertEqual(inv2['company_details']['bank_name'], 'HBL')
        self.assertEqual(inv2['company_details']['logo'], '')
        # Editing the company later never changes issued invoices.
        other.name = 'Renamed'
        other.save()
        fresh = self.client.get(f"/api/finance/invoices/{inv2['id']}/").data
        self.assertEqual(fresh['company_details']['name'], 'Gillani Traders')
        # A PATCH that doesn't touch the letterhead keeps it.
        res = self.client.patch(f"/api/finance/invoices/{inv2['id']}/", {'notes': 'x'}, format='json')
        self.assertEqual(res.data['company_details']['name'], 'Gillani Traders')
        # Switching company re-snapshots.
        res = self.client.patch(f"/api/finance/invoices/{inv2['id']}/", {'company': Company.load().id}, format='json')
        self.assertEqual(res.data['company_details']['name'], 'Syed Logistic')
        # Deleting a company keeps the invoice's letterhead.
        other.delete()
        kept = Invoice.objects.get(pk=inv['id'])
        self.assertEqual(kept.company_details['name'], 'Syed Logistic')

    def test_details_edited_for_one_document(self):
        details = {'name': 'Syed Logistic (Karachi)', 'phone': '021-555', 'address': 'Port Qasim',
                   'logo': '/static/img/logo.svg', 'unknown': 'dropped'}
        inv = self.invoice(company_details=details)
        self.assertEqual(inv['company_details']['name'], 'Syed Logistic (Karachi)')
        self.assertNotIn('unknown', inv['company_details'])
        self.assertEqual(Company.load().name, 'Syed Logistic')  # company itself unchanged
        for bad in ({'name': ''}, {'name': 'X', 'logo': 'https://evil.example/x.png'},
                    {'name': 'X', 'phone': 123}, 'not-an-object'):
            res = self.client.post('/api/finance/invoices/', invoice_payload(company_details=bad), format='json')
            self.assertEqual(res.status_code, 400, bad)

    def test_salary_slip_company(self):
        other = Company.objects.create(name='Gillani Traders')
        res = self.client.post('/api/finance/salary-slips/', slip_payload(company=other.id), format='json')
        self.assertEqual(res.status_code, 201, res.data)
        self.assertEqual(res.data['company_details']['name'], 'Gillani Traders')
        share = APIClient().get(f"/share/salary-slip/{res.data['share_token']}/")
        self.assertContains(share, 'Gillani Traders')

    def test_logo_upload_and_remove(self):
        company = Company.load()
        res = self.client.post(self.url + f'{company.id}/logo/', {'logo': real_png()}, format='multipart')
        self.assertEqual(res.status_code, 200, res.data)
        self.assertTrue(res.data['logo_url'].startswith('/media/companies/'))
        inv = self.invoice()
        self.assertEqual(inv['company_details']['logo'], res.data['logo_url'])
        bad = SimpleUploadedFile('x.png', b'not an image', content_type='image/png')
        self.assertEqual(self.client.post(self.url + f'{company.id}/logo/', {'logo': bad},
                                          format='multipart').status_code, 400)
        self.assertEqual(self.client.post(self.url + f'{company.id}/logo/', {},
                                          format='multipart').status_code, 400)
        res = self.client.delete(self.url + f'{company.id}/logo/')
        self.assertEqual(res.data['logo_url'], '/static/img/logo.svg')  # back to site logo
        # The invoice keeps the logo it was issued with.
        self.assertTrue(Invoice.objects.get(pk=inv['id']).company_details['logo'].startswith('/media/'))

    def test_legacy_company_profile_endpoint_edits_default(self):
        res = self.client.put('/api/finance/company-profile/', {'bank_iban': 'PK36'}, format='json')
        self.assertEqual(res.status_code, 200, res.data)
        self.assertEqual(Company.load().bank_iban, 'PK36')
