# Generated by Django 5.2.4 on 2026-06-26 16:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sur_name', models.CharField(max_length=255)),
                ('cnic', models.CharField(max_length=20, verbose_name='CNIC')),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_category', models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('other', 'Other')], default='retail', max_length=20)),
                ('meta_data', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficeExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('expense_type', models.CharField(choices=[('rent', 'Rent'), ('utilities', 'Utilities'), ('salary', 'Salary'), ('supplies', 'Supplies'), ('maintenance', 'Maintenance'), ('travel', 'Travel'), ('other', 'Other')], default='other', max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='expenses/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneralVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('invoice_date', models.DateField()),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit'), ('others', 'Others')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False, help_text='Payment received in full.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='finance.customer')),
            ],
            options={
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
    ]
