# Generated by Django 5.2.4 on 2026-06-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalvoucher',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit'), ('debit', 'Debit'), ('others', 'Others')], max_length=20),
        ),
    ]
