# Generated by Django 5.2.4 on 2026-06-26 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_generalvoucher_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField()),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank', 'Bank Transfer'), ('online', 'Online'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.generalvoucher')),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
