# Generated by Django 5.2.4 on 2026-06-26 17:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Default weight in kilograms.', max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default charge / unit price.', max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='generalvoucher',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Auto-generated (e.g. AYUI-78402410) if left blank.', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, help_text='Auto-generated (e.g. AYUI-78402410) if left blank.', max_length=100, unique=True)),
                ('shipment_number', models.CharField(blank=True, max_length=80)),
                ('order_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_orders', to='finance.customer')),
            ],
            options={
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='generalvoucher',
            name='sale_order',
            field=models.ForeignKey(blank=True, help_text='If set, this voucher is a receipt against that sale order.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='finance.saleorder'),
        ),
        migrations.CreateModel(
            name='SaleOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='finance.item')),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.saleorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
