# Generated by Django 5.2.4 on 2026-10-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_invoices_salary_slips'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Default quantity used when the item is added to a shipment or invoice line.'),
        ),
    ]
