# Generated by Django 5.2.4 on 2026-10-06 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


FIELDS = ('name', 'tagline', 'address', 'phone', 'email', 'website', 'ntn',
          'strn', 'bank_name', 'bank_account_title', 'bank_account_number',
          'bank_iban')


def backfill(apps, schema_editor):
    """Make the existing company the default (keeping the website logo on its
    letterhead) and stamp its details onto invoices / salary slips created
    before companies became selectable."""
    Company = apps.get_model('finance', 'CompanyProfile')
    company = Company.objects.order_by('pk').first()
    if company is None:
        return
    company.is_default = True
    company.use_site_logo = True
    company.save(update_fields=['is_default', 'use_site_logo'])
    snap = {f: getattr(company, f) or '' for f in FIELDS}
    snap['logo'] = settings.STATIC_URL + 'img/logo.svg'
    for model in ('Invoice', 'SalarySlip'):
        apps.get_model('finance', model).objects.filter(company__isnull=True)            .update(company=company, company_details=snap)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_item_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'ordering': ['-is_default', 'name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='companies/'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='use_site_logo',
            field=models.BooleanField(default=False, help_text='Print the website logo when no logo has been uploaded.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='finance.companyprofile'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_slips', to='finance.companyprofile'),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='company_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
