# Generated by Django 5.2.4 on 2025-08-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(help_text='Rating must be between 1 and 5 (1 being minimum and 5 being maximum)'),
        ),
    ]
